---
title: "Introduction"
them: lumen
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Longitudinal studies present many challenges such as participants follow-up (drop-outs, etc.) or correlation in the data. Indeed, repeated measures on the same subject over time induce intra-subject correlation. However, "standard" analysis methods such as linear or generalised linear regression assume independence of observations. They allow for inference on the average response trajectory over time and how its variation across treatments and other characteristics. Unfortunatelly, using them on correlated data can cause standard errors and be p-values to be innacurate and overall inference to be invalid. If a subject's observations are highly correlated in time, then the information on this subject is actually smaller than nj observations. A good way to deal with this issue is to use mixed modeling, an extension of linear models. Mixed models assume random errors within a subject and random variation in the trajectory across subjects. It allows to specify subjects specific intercept and slope. Mixed effects models overlap in many ways with hierarchical models\

We can define the random error called "within subjects" for measurement j of subject i as the deviation between Y_ij and the subject i trajectory.\
\
A simple mixed model for a longitudinal study involving a continuous response Y and time as predictor with random intercept and slope for time by subjects could be specified as the following:\

For i representing the index for subjects and j the index the index for time,

$$y_{i,j} = x_{i, j}\beta + \alpha_i \times Z_{i,j} +\epsilon_{i,j}$$
$x_{i, j}$ is the fixed effects vector (here intercept and time) for subject i at time j. $\beta$ is the vector of coefficients corresponding to these fixed effects.
$Z_{i,j}$ is the random effects vector (here a random intercept and a random slope for time) for subject i at time j.  
$\alpha_i$ is the vector of random coefficients for subject i. 
$\epsilon_{i,j} \sim N(0, \sigma^2)$ is the error for subject i at time j.

$$\alpha_i = {b_{0,i} \choose b_{1,i}} \sim N(0,
\begin{matrix}
  \tau_{11} & \tau_{12}\\
  \tau_{21} & \tau_{22} \end{matrix}) \:\perp \!\!\! \perp \: \epsilon_{i,j}$$


\
We could also have a model called a random intercept that would assumes different intercepts across subjects but parallel slopes by removing the random slope for time. Finally, when more than one predictor are involved, the effects of some variables might be different across subjects (include random slope) while others might not (only main fixed effect).\
\
The next tab goes over an example of the simple model with specified above as well as a more complex specification including multiple main effects, nested random effects and random slopes. The app also allows to visualize predictions for individual subjects as well as overall predictions for a new subject. The third tab extends the longitudinal analysis to cases where the errors within subjects are time dependent.\

<br>
\

#### References: \

- Arnab Maity, Longitudinal Data Analysis: Linear Mixed Effects
Models, NCSU Department of Statistics, 2020.\
<br>
- Peter D. Hoff, Lecture Notes on Hierarchical Modeling, 2019.\
<br>
- This analysis uses data from China Health and Nutrition Survey (CHNS). We thank the National Institute of Nutrition and Food Safety, China Center for Disease Control and Prevention, Carolina Population Center, the University of North Carolina at Chapel Hill, the NIH (R01-HD30880, DK056350, and R01-HD38700) and the Fogarty International Center, NIH for financial support for the CHNS data collection and analysis files from 1989 to 2006 and both parties plus the China-Japan Friendship Hospital, Ministry of Health for support for CHNS 2009 and future surveys.
